version: "3"
services:
  validator:
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: always
    container_name: validator
    volumes:
      - ./validator:/home/parity/.local/share/io.parity.ethereum
    restart: unless-stopped
    entrypoint: /start.sh
    environment:
      # CHANGE NAT_IP to your IP
      NAT_IP: 95.7.132.244
      # If you have multiple addresses, you can specify one address for the authority node.
      # AUTH_ADDRESS: "ab59a1ea1ac9af9f77518b9b4ad80942ade35088"
    user: "0:0"
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
